import structlog
from datetime import datetime
from typing import Dict, Any, List
from market_agent.research.rss_researcher import RSSResearcher
from market_agent.research.social_scraper import SocialScraper
from market_agent.research.vector_engine import VectorEngine
from market_agent.data.storage.postgres import PostgresStorage

logger = structlog.get_logger()

class ResearchCoordinator:
    """
    Layer 7 & 8 COORDINATOR
    Orchestrates the research flow:
    1. Triggers RSS & Social scans.
    2. Embeds findings via VectorEngine.
    3. Searches historical 'Market Situations' for grounding.
    4. Stores results in Long-Term Memory.
    """
    def __init__(self, storage: PostgresStorage):
        self.storage = storage
        self.rss = RSSResearcher()
        self.social = SocialScraper()
        self.vector_engine = VectorEngine()

    def perform_deep_research(self, task: Dict[str, Any], symbol: str, regime: str, metrics: dict):
        """
        Executes a research task generated by the Curiosity Engine.
        """
        logger.info("starting_deep_research", task_id=task.get("id"), reason=task.get("reason"))
        
        # 1. RSS Scan
        news_items = self.rss.fetch_latest_news(symbol)
        headline_summary = " | ".join([item["title"] for item in news_items[:3]])
        
        # 2. Social Scan
        sentiment_data = self.social.scrape_sentiment(symbol)
        
        # 3. Vector Embedding & Situational Matching
        # Embed the current market state + news context
        full_context = f"Regime: {regime} | News: {headline_summary} | Social: {sentiment_data['overall_sentiment']}"
        situation_vec = self.vector_engine.encode(full_context)[0]
        
        # Search Library for similar past events
        similar_past = self.storage.search_similar_situations(situation_vec, limit=2)
        
        # 4. Synthesize Finding
        finding = f"Found {len(news_items)} relevant news items. Social sentiment is {sentiment_data['overall_sentiment']}."
        if similar_past:
            finding += f" Grounding: Similar to historical event at {similar_past[0].timestamp}."
            
        # 5. Store in Long-Term Memory
        self.storage.store_situation(
            symbol=symbol,
            timestamp=datetime.now(),
            embedding=situation_vec.tolist(),
            context=full_context,
            finding=finding,
            regime=regime
        )
        
        logger.info("research_complete_and_stored", task_id=task.get("id"))
        return finding

if __name__ == "__main__":
    from datetime import datetime
    storage = PostgresStorage()
    coordinator = ResearchCoordinator(storage)
    
    # Mock task
    mock_task = {"id": "REQ_TEST", "reason": "Logic Contradiction"}
    metrics = {"volatility": 0.002, "atr": 12.0}
    
    # Run research
    # NOTE: In a real run, this fetches real live news!
    result = coordinator.perform_deep_research(mock_task, "ITC.NS", "BULL_TREND", metrics)
    print(f"\nFinal Research Finding: {result}")
